sudo: required
services:
  - docker

before_install:
  - docker build -t salilchhetri/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run salilchhetri/docker-kubernetes npm run test -- --coverage
